"""Added Company, Dev, Freebie models

Revision ID: 9b8af5e2efaf
Revises: 0158fa6a3759
Create Date: 2025-03-04 10:01:07.349611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8af5e2efaf'
down_revision = '0158fa6a3759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
